stages:
  - runner_startup
  - build_and_deploy
  - cleanup_runner
  - runner_shutdown

variables:
  AWS_DEFAULT_REGION: "ap-south-1" # mumbai region for AWS
  PROD_IMAGE_NAME: "registry.gitlab.com/dodo1604703/dodobe/production"
  DEV_IMAGE_NAME: "registry.gitlab.com/dodo1604703/dodobe/development"
  # The production auto scaling group is set to pick image with tag publish only
  PROD_IMAGE_TAG: "publish" # Don't change this
  DEV_IMAGE_TAG: "${CI_COMMIT_TAG}"

# cache node modules for faster builds
cache:
  paths:
    - node_modules/

# start the runner for image building
start_ec2:
  stage: runner_startup
  image: python:3.9
  script:
    - pip install boto3
    - python -c "import boto3; boto3.client('sts').get_caller_identity()"
    - python start_ec2.py

# Build the image for the application and push to dockerhub
build_deploy_prod:
  stage: build_and_deploy
  tags:
    - dodo-group-runner
  image: bitnami/git:latest
  # Run the branch only if the commit tag has regex like production-*( starting with production )
  rules:
    - if: "$CI_COMMIT_TAG =~ /^production-.*$/"
      when: always
    - when: never
  before_script:
    - unset DOCKER_HOST
    - docker login $GITLAB_REGISTRY -u $GITLAB_USERNAME -p $REGISTRY_PASSWORD
  script:
    - docker build -t $PROD_IMAGE_NAME:$PROD_IMAGE_TAG --file=Dockerfile .
    - docker images
    - docker push $PROD_IMAGE_NAME:$PROD_IMAGE_TAG
    - aws autoscaling start-instance-refresh --auto-scaling-group-name dodo-backend-backup-asg
    - docker tag $PROD_IMAGE_NAME:$PROD_IMAGE_TAG $PROD_IMAGE_NAME:$(date +%Y-%m-%d)
    - docker push $PROD_IMAGE_NAME:$(date +%Y-%m-%d)

build_deploy_dev:
  stage: build_and_deploy
  # Tag for the runner to pick this job
  tags:
    - dodo-group-runner
  image: bitnami/git:latest
  rules:
    - if: "$CI_COMMIT_TAG =~ /^development-v.*$/"
      when: always
    - when: never
  before_script:
    - unset DOCKER_HOST
    - docker login $GITLAB_REGISTRY -u $GITLAB_USERNAME -p $REGISTRY_PASSWORD
  script:
    - docker build -t $DEV_IMAGE_NAME:$DEV_IMAGE_TAG .
    - docker images
    - docker push $DEV_IMAGE_NAME:$DEV_IMAGE_TAG
    # Tag the development image with custom tag
    - docker tag $DEV_IMAGE_NAME:$DEV_IMAGE_TAG $DEV_IMAGE_NAME:$(date +%Y-%m-%d)
    - docker push $DEV_IMAGE_NAME:$(date +%Y-%m-%d)

# Cleanup runner for any image
deprecated_image:
  stage: cleanup_runner
  tags:
    - dodo-group-runner
  script:
    - docker image prune -a --filter "until=48h" -f
    - docker rmi -f $(docker images -q) || true
    - echo "Updated list of image in RUNNER instance"
    - docker images

# stop the runner after deployment
stop_ec2:
  stage: runner_shutdown
  image: python:3.9
  script:
    - pip install boto3
    - python stop_ec2.py
