stages:
  - runner_up
  - build
  - test
  - deploy_dev
  - deploy_prd
  - cleanup
  - runner_down

variables:
  AWS_DEFAULT_REGION: 'ap-south-1' # mumbai region for AWS
  IMAGE_TAG: 'dev-backend'

# cache node modules for faster builds
cache:
  paths:
    - node_modules/
  
# start the runner for image building foundation
.start_ec2:
  stage: runner_up
  image: python:3.9
  script:
    - pip install boto3
    - python -c "import boto3; boto3.client('sts').get_caller_identity()"
    - python start_ec2.py

# Build the image for the application and push to dockerhub
.build-application:
  stage: build
  tags:
    - dodo-group-runner
  before_script:
    - unset DOCKER_HOST
    - docker login -u $GITLAB_USERNAME -p $REGISTRY_PASSWORD $GITLAB_REGISTRY
  script:
    - docker build -t registry.gitlab.com/dodo1604703/dodobe/feat/refactor .
    - docker images
    - docker push registry.gitlab.com/dodo1604703/dodobe/feat/refactor

deploy_to_development:
  stage: deploy_dev
  tags: 
    - dodo-group-runner
  script:
    - echo "$SSH_PRIVATE_KEY" > dodokey.pem
    - chmod 600 dodokey.pem
#    - ssh -o StrictHostKeyChecking=no -i dodokey.pem ubuntu@ec2-35-154-103-10.ap-south-1.compute.amazonaws.com "docker pull hello-world"
    - ssh -o StrictHostKeyChecking=no -i dodokey.pem ubuntu@ec2-35-154-103-10.ap-south-1.compute.amazonaws.com << 'EOF'
      docker login -u "$GITLAB_USERNAME" -p "$REGISTRY_PASSWORD" "$GITLAB_REGISTRY"
      docker pull "$CI_REGISTRY_IMAGE:latest"
      docker images
      EOF

# remove image older than 48h from runner
deprecated_image:
  stage: cleanup
  tags: 
    - dodo-group-runner
  script:
    - docker image prune -a --filter "until=48h" -f
    - echo "Updated list of image in RUNNER instance"
    - docker images

# stop the runner after deployment
.stop_ec2:
  stage: runner_down
  image: python:3.9
  script:
    - pip install boto3
    - python stop_ec2.py
